name: build_and_test

on:
  push:
    branches:
      - main
      - lsst-dev
      - master
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: Install dependencies
        # Might be quicker to install rubin-env plus any necessary additions.
        shell: bash -l {0}
        run: |
          conda install -y -q 'setuptools<70' 'numpy<1.22' scipy 'matplotlib<3.7' pandas llvmlite numba astropy 'photutils<1.5' astroquery coloredlogs scikit-image h5py emcee tqdm schwimmbad iminuit coverage configparser coveralls pysynphot deprecated pyyaml 'pytest<8.2'

      - name: List installed packages
        shell: bash -l {0}
        run: |
          conda list
          pip list -v

      - name: Build and install
        shell: bash -l {0}
        run: |
          pip install -v -e .

      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest --log-cli-level=INFO tests

      - name: Run full chain
        shell: bash -l {0}
        run: |
          pytest tests/test_fullchain.py --log-cli-level=INFO --cov --cov-report lcov
